@baseUrl = https://ymm-fantasy-map.herokuapp.com/api
@authCookie = AccessToken=s%3AeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NywiZW1haWwiOiJtQHVyaWNpby5jb20iLCJuYW1lIjoiTWF1cmljaW8gVG9tYXoiLCJpYXQiOjE2NzA2MzA2MjQsImV4cCI6MTY3MDY3MzgyNH0.2_t494ZOhYx0DOE76ey6kM5EHu6L-YTJCGh9hmLXL2U.tpVHE9tS5HjpN%2BXvglrJ%2FLwuPzgZ3UAvoB4IvrSrsDQ

### Lists

GET {{baseUrl}}/lists/18
Cookie: {{authCookie}}

###

GET {{baseUrl}}/lists/popular

###

GET {{baseUrl}}/lists/search?query=wine

###

GET {{baseUrl}}/lists/category/1

###

POST {{baseUrl}}/lists
Cookie: {{authCookie}}
Content-Type: application/json

{
  "name": "A new interesting list",
  "description": "Find nice places to enjoy with your beloved ones.",
  "picture": "https://media.istockphoto.com/id/865208774/photo/romantic-dining-at-night.jpg?s=612x612&w=0&k=20&c=Ege0ISa8UanWiqUMDvHLAfIcNhnw42CZdSRevM-NVmk=",
  "categoryId": 3,
  "placeIds": [1, 4]
}

###

PUT {{baseUrl}}/lists/13
Cookie: {{authCookie}}
Content-Type: application/json

{
  "name": "New interesting list",
  "description": "Find nice places to enjoy with your beloved ones.",
  "picture": "https://media.istockphoto.com/id/865208774/photo/romantic-dining-at-night.jpg?s=612x612&w=0&k=20&c=Ege0ISa8UanWiqUMDvHLAfIcNhnw42CZdSRevM-NVmk=",
  "categoryId": 3,
  "placeIds": [1, 4]
}

###

DELETE {{baseUrl}}/lists/13
Cookie: {{authCookie}}

### Places

GET {{baseUrl}}/places/4
Cookie: {{authCookie}}

###

GET {{baseUrl}}/places
Cookie: {{authCookie}}

###

POST {{baseUrl}}/places
Cookie: {{authCookie}}
content-type: application/json

{
  "name": "Empire State",
  "address": "New York, NY 10001, USA",
  "location": {
    "lat": 40.748691482594346,
    "lng": -73.985731315646
  },
  "description": "Iconic, art deco office tower from 1931 with exhibits & observatories on the 86th & 102nd floors.",
  "picture": "https://media.timeout.com/images/101705309/image.jpg",
  "listId": 1
}

###

PUT {{baseUrl}}/places/4
Cookie: {{authCookie}}
content-type: application/json

{
  "name": "The Empire State",
  "address": "New York, NY 10001, USA",
  "location": {
    "lat": 40.748691482594346,
    "lng": -73.985731315646
  },
  "description": "Iconic, art deco office tower from 1931 with exhibits & observatories on the 86th & 102nd floors.",
  "picture": "https://media.timeout.com/images/101705309/image.jpg"
}

###

DELETE {{baseUrl}}/places/5
Cookie: {{authCookie}}

### Files

POST {{baseUrl}}/files/upload
Cookie: {{authCookie}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="filetoupload"; filename="test-image.jpg"
Content-Type: image/jpeg

< ./test-image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Reviews

GET {{baseUrl}}/reviews/
Cookie: {{authCookie}}

###

POST {{baseUrl}}/reviews/
Cookie: {{authCookie}}
content-type: application/json

{
  "content": "It is one of my favorites!",
  "stars": 5,
  "placeId": 4
}

###

PUT {{baseUrl}}/reviews/8
Cookie: {{authCookie}}
content-type: application/json

{
  "content": "It is The best!",
  "stars": 5
}

###

DELETE {{baseUrl}}/reviews/8
Cookie: {{authCookie}}

### Favorites

PUT {{baseUrl}}/favorites/4
Cookie: {{authCookie}}

### Users

GET {{baseUrl}}/users/profile
Cookie: {{authCookie}}

###

POST {{baseUrl}}/users/signup
content-type: application/json

{
  "name": "Franklyn",
  "email": "fran@gmaii.com",
  "password": "Amaz1-ng",
  "profilePicture": "https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.pngfind.com%2Fmpng%2FhiJwTJo_icon-user-icon-hd-png-download%2F&psig=AOvVaw2Ky-6ZUslVpDI-6qFOaM9p&ust=1668748375935000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCKiO96S6tPsCFQAAAAAdAAAAABAE"
}

###

POST {{baseUrl}}/users/signin
content-type: application/json

{
  "username": "m@uricio.com",
  "password": "Maur1c10"
}

###

PUT {{baseUrl}}/users/profile
Cookie: {{authCookie}}
content-type: application/json

{
  "name": "Jack Johnson",
  "profilePicture": "https://www.w3schools.com/howto/img_avatar.png",
  "location": "Vancouver, BC",
  "description": "She can make angels"
}
