@baseUrl = http://localhost:3001/api

### Lists

GET {{baseUrl}}/lists/1

###

GET {{baseUrl}}/lists/popular

###

GET {{baseUrl}}/lists/search?query=wine

### Places

GET {{baseUrl}}/places/5

###

POST {{baseUrl}}/places
content-type: application/json

{
  "name": "Empire State",
  "address": "New York, NY 10001, USA",
  "location": {
    "lat": 40.748691482594346,
    "lng": -73.985731315646
  },
  "description": "Iconic, art deco office tower from 1931 with exhibits & observatories on the 86th & 102nd floors.",
  "picture": "https://media.timeout.com/images/101705309/image.jpg",
  "listId": 1
}

###

PUT {{baseUrl}}/places/5
content-type: application/json

{
  "name": "The Empire State",
  "address": "New York, NY 10001, USA",
  "location": {
    "lat": 40.748691482594346,
    "lng": -73.985731315646
  },
  "description": "Iconic, art deco office tower from 1931 with exhibits & observatories on the 86th & 102nd floors.",
  "picture": "https://media.timeout.com/images/101705309/image.jpg"
}

###

DELETE {{baseUrl}}/places/5

### Files

POST {{baseUrl}}/files/upload
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="filetoupload"; filename="test-image.jpg"
Content-Type: image/png

< ./test-image.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
